version: '3.5'
services:
  postgres:
    image: postgres:13
    restart: always
    container_name: mydatabase
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}


  backend:
    build:  ./Backend/
    container_name: Backend
    environment:
      URI: ${URI}
      UID: ${UID}
      SECRET: ${SECRET}
      NEST_APP_HOST: ${NEST_APP_HOST}
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      HOME_URL: ${HOME_URL}
    ports:
      - '3000:3000'
      - '5555:5555'
    depends_on:
      - postgres
    volumes:
      - /nfs/homes/aait-mas/volumes/uploads:/Backend/uploads

  frontend:
    build: ./Frontend/
    container_name: Frontend
    volumes:
      - ./Frontend:/app
    ports:
      - '5173:5173'
    environment:
      URI: ${URI}
    depends_on:
      - backend

volumes:
  postgres: